const state = {
  token: '',
  me: null, overview: null, products: [], orders: [], customers: [], categories: [], brands: [], coupons: [],
  homepage: [], slides: [], ads: [], users: [], activity: [], settings: null,
};
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = (v='') => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = v => `${Number(v || 0).toLocaleString('en-US',{maximumFractionDigits:2})} د.ل`;
const dateTime = ts => ts ? new Date(ts*1000).toLocaleString('ar-LY') : '—';
const dateInput = ts => ts ? new Date(ts*1000).toISOString().slice(0,16) : '';
const toTs = v => v ? Math.floor(new Date(v).getTime()/1000) : null;
const DEFAULT_POPUP_IMAGE_URL = 'https://i.postimg.cc/26sT42KJ/92347da3-51f4-47df-9c1b-2725fed110be.png';
const DEFAULT_CART_DISCOUNT_PERCENT = 10;
function boolSetting(value, fallback=false){if(value===undefined||value===null||value==='')return fallback;if(typeof value==='boolean')return value;if(typeof value==='number')return value===1;return ['1','true','yes','on','enabled'].includes(String(value).trim().toLowerCase())}
function percentSetting(value, fallback=0){const n=Number(value);return Number.isFinite(n)?Math.min(100,Math.max(0,n)):fallback}
function settingHas(settings,...keys){const s=settings&&typeof settings==='object'?settings:{};return keys.some(k=>Object.prototype.hasOwnProperty.call(s,k))}
function settingValue(settings,...keys){const s=settings&&typeof settings==='object'?settings:{};for(const k of keys){if(Object.prototype.hasOwnProperty.call(s,k))return s[k]}return undefined}

async function api(path, options={}) {
  if (!window.SwitchesSupabaseAdmin) throw new Error('ملفات Supabase غير محملة.');
  try {
    return await window.SwitchesSupabaseAdmin.request(path, options);
  } catch (error) {
    if (String(error?.message || '').includes('تسجيل الدخول')) logout(false);
    throw error;
  }
}
async function saveSettingsPatch(patch){
  const payload={...(state.settings||{}),...(patch||{})};
  await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(payload)});
  state.settings=payload;
}
async function uploadImageInput(inputSelector, hintSelector){
  const input=$(inputSelector), hint=hintSelector?$(hintSelector):null;
  if(!input?.files?.length)return '';
  if(hint)hint.textContent='جارٍ رفع الصورة...';
  const fd=new FormData();fd.append('file',input.files[0]);
  const uploaded=await api('/api/admin/uploads',{method:'POST',body:fd});
  if(hint)hint.textContent='تم رفع الصورة.';
  return uploaded.url;
}
function toast(message, error=false){
  const el=document.createElement('div'); el.className=`toast${error?' error':''}`; el.textContent=message; $('#toastRoot').appendChild(el); setTimeout(()=>el.remove(),3500);
}
function showAuth(){ $('#authShell').classList.remove('hidden'); $('#appShell').classList.add('hidden'); }
function showApp(){ $('#authShell').classList.add('hidden'); $('#appShell').classList.remove('hidden'); $('#loggedUserLabel').textContent=`${state.me.username} · ${state.me.role}`; applyRoleUI(); }
function logout(show=true){ state.token=''; state.me=null; localStorage.removeItem('switches_admin_token'); window.SwitchesSupabaseAdmin?.signOut?.(); showAuth(); if(show)toast('تم تسجيل الخروج'); }
function applyRoleUI(){
  $$('.owner-only').forEach(x=>x.classList.toggle('hidden',state.me?.role!=='owner'));
  $$('.admin-only').forEach(x=>x.classList.toggle('hidden',!['owner','admin'].includes(state.me?.role)));
}
function openModal(title, html, onSubmit){ $('#modalTitle').textContent=title; const form=$('#modalForm'); form.innerHTML=html; form.onsubmit=onSubmit||null; $('#modal').classList.remove('hidden'); }
function closeModal(){ $('#modal').classList.add('hidden'); $('#modalForm').innerHTML=''; }
$$('[data-close]').forEach(x=>x.addEventListener('click', closeModal));

const titles={dashboard:'Dashboard',products:'المنتجات',orders:'الطلبات',customers:'العملاء',stock:'المخزون',categories:'التصنيفات',brands:'الماركات',coupons:'الكوبونات',homepage:'إدارة الصفحة الرئيسية',banners:'البانرات والإعلانات',users:'المستخدمون والصلاحيات',activity:'سجل النشاط',settings:'الإعدادات'};
function switchSection(key){
  $$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===key));
  $$('.section-panel').forEach(p=>p.classList.toggle('active',p.id===`section-${key}`));
  $('#sectionTitle').textContent=titles[key]||key; $('#sidebar').classList.remove('open');
}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchSection(b.dataset.section)));
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#logoutBtn').addEventListener('click',()=>logout());

$('#loginForm').addEventListener('submit', async e=>{
  e.preventDefault(); const f=e.currentTarget;
  try{ const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:f.username.value.trim(),password:f.password.value})}); state.token=d.token||''; await boot(); }
  catch(err){toast(err.message,true)}
});

async function boot(){
  try{
    state.me=await api('/api/admin/me'); showApp(); await loadAll();
  }catch(err){toast(err.message,true)}
}
async function loadAll(){
  const tasks=[
    ['overview','/api/admin/overview'],['products','/api/admin/products'],['orders','/api/admin/orders'],['customers','/api/admin/customers'],
    ['categories','/api/admin/categories'],['brands','/api/admin/brands'],['coupons','/api/admin/coupons'],['homepage','/api/admin/homepage'],
    ['slides','/api/admin/hero-slides'],['ads','/api/admin/ads'],['settings','/api/admin/settings']
  ];
  if(['owner','admin'].includes(state.me.role)) tasks.push(['activity','/api/admin/activity?limit=100']);
  if(state.me.role==='owner') tasks.push(['users','/api/admin/users']);
  const values=await Promise.all(tasks.map(([,url])=>api(url))); tasks.forEach(([k],i)=>state[k]=values[i]); renderAll();
}
function renderAll(){ renderOverview(); renderProducts(); renderOrders(); renderCustomers(); renderStock(); renderEntities(); renderCoupons(); renderHomepage(); renderBanners(); renderUsers(); renderActivity(); renderSettings(); fillFilters(); }
$('#refreshBtn').addEventListener('click',async()=>{try{await loadAll();toast('تم التحديث')}catch(e){toast(e.message,true)}});
$('#exportBtn').addEventListener('click',async()=>{try{const d=await api('/api/admin/export');const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`switches-export-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)}catch(e){toast(e.message,true)}});

function renderOverview(){
  const o=state.overview||{}; const cards=[
    ['إجمالي المبيعات',money(o.totalSales),'fa-coins'],['مبيعات اليوم',money(o.todaySales),'fa-calendar-day'],['مبيعات الشهر',money(o.monthSales),'fa-calendar'],
    ['الطلبات',o.orders||0,'fa-cart-shopping'],['طلبات جديدة',o.newOrders||0,'fa-bell'],['المنتجات',o.products||0,'fa-box'],
    ['مخزون منخفض',o.lowStock||0,'fa-triangle-exclamation'],['نفد المخزون',o.outOfStock||0,'fa-ban'],['العملاء',o.customers||0,'fa-users'],['مكتملة',o.completedOrders||0,'fa-circle-check']
  ];
  $('#metricsGrid').innerHTML=cards.map(c=>`<article class="metric-card"><div class="metric-icon"><i class="fa-solid ${c[2]}"></i></div><small>${c[0]}</small><strong>${c[1]}</strong></article>`).join('');
  const trend=o.salesTrend||[]; const max=Math.max(1,...trend.map(x=>x.value));
  $('#salesChart').innerHTML=trend.map(x=>`<div class="bar-col"><small>${Number(x.value).toLocaleString('en-US')}</small><div class="bar" style="height:${Math.max(4,x.value/max*160)}px"></div><span>${x.label}</span></div>`).join('');
  $('#alertsList').innerHTML=(o.alerts||[]).length?(o.alerts||[]).map(a=>`<div class="alert-item"><span><i class="fa-solid fa-circle-exclamation"></i> ${esc(a.text)}</span></div>`).join(''):'<div class="quick-row">لا توجد تنبيهات حالياً</div>';
  $('#latestOrders').innerHTML=ordersTable(o.latestOrders||[],false);
}
function badge(text,type=''){return `<span class="badge ${type}">${esc(text)}</span>`}
function statusLabel(s){return ({new:'طلب جديد',confirmed:'تم التأكيد',preparing:'قيد التجهيز',ready:'جاهز',shipped:'تم الشحن',completed:'مكتمل',cancelled:'ملغي',canceled:'ملغي'})[s]||s}
function productStatusLabel(s){return ({published:'منشور',draft:'مسودة',hidden:'مخفي'})[s]||s}
function stockBadge(p){ if(!p.trackStock)return badge('غير متتبع'); if(p.stockQty<=0)return badge('نفد','bad'); if(p.stockQty<=p.lowStockThreshold)return badge(`منخفض ${p.stockQty}`,'warn'); return badge(`متوفر ${p.stockQty}`,'good'); }
function productImage(p){return p.images?.[0]?`<img class="thumb" src="${esc(p.images[0])}" onerror="this.style.display='none'">`:`<div class="thumb placeholder"><i class="fa-solid fa-image"></i></div>`}

function fillFilters(){ $('#productCategoryFilter').innerHTML='<option value="">كل التصنيفات</option>'+state.categories.map(c=>`<option>${esc(c.name)}</option>`).join(''); }
function renderProducts(){
  const q=($('#productSearch')?.value||'').toLowerCase(), cat=$('#productCategoryFilter')?.value||'', st=$('#productStatusFilter')?.value||'';
  const rows=state.products.filter(p=>(!q||[p.name,p.sku,p.brand,p.category].join(' ').toLowerCase().includes(q))&&(!cat||p.category===cat)&&(!st||p.status===st));
  $('#productsBody').innerHTML=rows.length?rows.map(p=>`<tr><td>${productImage(p)}</td><td><strong>${esc(p.name)}</strong><br><small>${esc(p.brand)}</small></td><td>${esc(p.sku||'—')}</td><td>${esc(p.category||'—')}</td><td>${money(p.price)}${p.oldPrice?`<br><small><s>${money(p.oldPrice)}</s></small>`:''}</td><td>${stockBadge(p)}</td><td>${badge(productStatusLabel(p.status),p.status==='published'?'good':'')}</td><td><div class="row-actions"><button class="btn small" onclick="openProductEditor(${p.id})">تعديل</button><button class="btn small" onclick="duplicateProduct(${p.id})">نسخ</button>${['owner','admin'].includes(state.me?.role)?`<button class="btn small ghost danger-text" onclick="deleteProduct(${p.id})">حذف</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="8">لا توجد منتجات.</td></tr>';
}
$('#productSearch').addEventListener('input',renderProducts);$('#productCategoryFilter').addEventListener('change',renderProducts);$('#productStatusFilter').addEventListener('change',renderProducts);
$('#addProductBtn').addEventListener('click',()=>openProductEditor());
window.openProductEditor=function(id){
  const p=id?state.products.find(x=>x.id===id):null;
  const x=p||{name:'',shortDescription:'',description:'',category:'',brand:'',sku:'',price:0,oldPrice:null,condition:'جديد',images:[],specs:{},tags:[],stockQty:0,lowStockThreshold:3,trackStock:true,availability:'available',status:'published',seoTitle:'',metaDescription:'',slug:'',isActive:true,sortOrder:0};
  const cats=state.categories.map(c=>`<option ${x.category===c.name?'selected':''}>${esc(c.name)}</option>`).join('');
  const brands=state.brands.map(c=>`<option ${x.brand===c.name?'selected':''}>${esc(c.name)}</option>`).join('');
  openModal(id?'تعديل المنتج':'إضافة منتج جديد',`<div class="form-grid three">
    <label><span>اسم المنتج</span><input name="name" value="${esc(x.name)}" required></label><label><span>SKU</span><input name="sku" value="${esc(x.sku)}"></label><label><span>الحالة</span><select name="status"><option value="published" ${x.status==='published'?'selected':''}>منشور</option><option value="draft" ${x.status==='draft'?'selected':''}>مسودة</option><option value="hidden" ${x.status==='hidden'?'selected':''}>مخفي</option></select></label>
    <label><span>التصنيف</span><select name="category"><option value="">بدون</option>${cats}</select></label><label><span>الماركة</span><select name="brand"><option value="">بدون</option>${brands}</select></label><label><span>حالة المنتج</span><select name="availability"><option value="available" ${x.availability==='available'?'selected':''}>متوفر</option><option value="unavailable" ${x.availability==='unavailable'?'selected':''}>غير متوفر</option><option value="outOfStock" ${x.availability==='outOfStock'?'selected':''}>نفذت الكمية</option><option value="comingSoon" ${x.availability==='comingSoon'?'selected':''}>قريبًا</option></select></label>
    <label><span>حالة القطعة</span><select name="condition"><option value="جديد" ${x.condition==='جديد'?'selected':''}>جديد</option><option value="مستعمل" ${x.condition==='مستعمل'?'selected':''}>مستعمل</option><option value="علبة مفتوحة" ${x.condition==='علبة مفتوحة'?'selected':''}>علبة مفتوحة</option></select></label>
    <label><span>السعر الحالي</span><input name="price" type="number" step="0.01" value="${x.price}"></label><label><span>السعر القديم</span><input name="oldPrice" type="number" step="0.01" value="${x.oldPrice??''}"></label><label><span>الترتيب</span><input name="sortOrder" type="number" value="${x.sortOrder||0}"></label>
    <label><span>المخزون</span><input name="stockQty" type="number" value="${x.stockQty||0}"></label><label><span>حد التنبيه</span><input name="lowStockThreshold" type="number" value="${x.lowStockThreshold||3}"></label><label><span>تتبع المخزون</span><select name="trackStock"><option value="1" ${x.trackStock?'selected':''}>نعم</option><option value="0" ${!x.trackStock?'selected':''}>لا</option></select></label>
    <label class="full"><span>وصف مختصر</span><input name="shortDescription" value="${esc(x.shortDescription)}"></label><label class="full"><span>الوصف الكامل</span><textarea name="description" rows="5">${esc(x.description)}</textarea></label>
    <div class="full upload-box"><label><span>صور المنتج (روابط - كل سطر صورة)</span><textarea name="images" rows="4">${esc((x.images||[]).join('\n'))}</textarea></label><label><span>أو ارفع صورة من جهازك</span><input id="productImageUpload" type="file" accept="image/*" multiple></label><div id="uploadHint" class="hint"></div></div>
    <label class="full"><span>المواصفات (كل سطر: المفتاح = القيمة)</span><textarea name="specs" rows="5">${esc(Object.entries(x.specs||{}).map(([k,v])=>`${k} = ${v}`).join('\n'))}</textarea></label>
    <label class="full"><span>Tags مفصولة بفواصل</span><input name="tags" value="${esc((x.tags||[]).join(', '))}"></label>
    <label><span>SEO Title</span><input name="seoTitle" value="${esc(x.seoTitle)}"></label><label><span>URL Slug</span><input name="slug" value="${esc(x.slug)}"></label><label><span>مفعل</span><select name="isActive"><option value="1" ${x.isActive?'selected':''}>نعم</option><option value="0" ${!x.isActive?'selected':''}>لا</option></select></label>
    <label class="full"><span>Meta Description</span><textarea name="metaDescription" rows="3">${esc(x.metaDescription)}</textarea></label>
    <div class="full row-actions"><button class="btn primary" type="submit">${id?'حفظ التعديلات':'إضافة المنتج'}</button>${id?`<button class="btn ghost" type="button" onclick="window.open('/?product=${id}','_blank')"><i class="fa-solid fa-eye"></i> معاينة المنتج</button>`:''}</div></div>`,async e=>{
      e.preventDefault();const f=e.currentTarget;let images=f.images.value.split('\n').map(s=>s.trim()).filter(Boolean);
      const files=$('#productImageUpload').files; if(files.length){$('#uploadHint').textContent='جارٍ رفع الصور...';for(const file of files){const fd=new FormData();fd.append('file',file);const up=await api('/api/admin/uploads',{method:'POST',body:fd});images.push(up.url)}}
      const specs={};f.specs.value.split('\n').forEach(line=>{const i=line.indexOf('=');if(i>0)specs[line.slice(0,i).trim()]=line.slice(i+1).trim()});
      const payload={name:f.name.value.trim(),shortDescription:f.shortDescription.value.trim(),description:f.description.value.trim(),category:f.category.value,brand:f.brand.value,sku:f.sku.value.trim(),price:+f.price.value||0,oldPrice:f.oldPrice.value?+f.oldPrice.value:null,condition:f.condition.value,images,specs,tags:f.tags.value.split(',').map(s=>s.trim()).filter(Boolean),stockQty:+f.stockQty.value||0,lowStockThreshold:+f.lowStockThreshold.value||3,trackStock:f.trackStock.value==='1',availability:f.availability.value,status:f.status.value,seoTitle:f.seoTitle.value.trim(),metaDescription:f.metaDescription.value.trim(),slug:f.slug.value.trim(),isActive:f.isActive.value==='1',sortOrder:+f.sortOrder.value||0};
      try{await api(id?`/api/admin/products/${id}`:'/api/admin/products',{method:id?'PUT':'POST',body:JSON.stringify(payload)});closeModal();await refreshCore();toast(id?'تم تحديث المنتج':'تمت إضافة المنتج')}catch(err){toast(err.message,true)}
  });
};
window.duplicateProduct=async id=>{try{await api(`/api/admin/products/${id}/duplicate`,{method:'POST'});await refreshCore();toast('تم نسخ المنتج')}catch(e){toast(e.message,true)}};
window.deleteProduct=async id=>{if(!confirm('هل أنت متأكد من حذف هذا المنتج؟ سيتم استخدام Soft Delete.'))return;try{await api(`/api/admin/products/${id}`,{method:'DELETE'});await refreshCore();toast('تم حذف المنتج')}catch(e){toast(e.message,true)}};
async function refreshCore(){ const [overview,products,homepage,categories,brands]=await Promise.all([api('/api/admin/overview'),api('/api/admin/products'),api('/api/admin/homepage'),api('/api/admin/categories'),api('/api/admin/brands')]);Object.assign(state,{overview,products,homepage,categories,brands});renderOverview();renderProducts();renderStock();renderHomepage();renderEntities();fillFilters(); }

function ordersTable(rows,actions=true){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>العميل</th><th>الهاتف</th><th>الإجمالي</th><th>الحالة</th><th>التاريخ</th>${actions?'<th>تحكم</th>':''}</tr></thead><tbody>${rows.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.fullName)}</td><td>${esc(o.phone)}</td><td>${money(o.total)}</td><td>${badge(statusLabel(o.status),o.status==='completed'?'good':o.status==='new'?'warn':'')}</td><td>${dateTime(o.createdAt)}</td>${actions?`<td><button class="btn small" onclick="openOrder(${o.id})">فتح</button></td>`:''}</tr>`).join('')||'<tr><td colspan="7">لا توجد طلبات.</td></tr>'}</tbody></table></div>`}
function renderOrders(){ $('#ordersBody').innerHTML=state.orders.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.fullName)}</td><td>${esc(o.phone)}</td><td>${money(o.total)}</td><td>${esc(o.paymentMethod)}</td><td>${badge(statusLabel(o.status),o.status==='completed'?'good':o.status==='new'?'warn':'')}</td><td>${dateTime(o.createdAt)}</td><td><button class="btn small" onclick="openOrder(${o.id})">تفاصيل</button></td></tr>`).join('')||'<tr><td colspan="8">لا توجد طلبات.</td></tr>'; }
window.openOrder=function(id){const o=state.orders.find(x=>x.id===id);if(!o)return;openModal(`الطلب #${id}`,`<div class="form-grid"><div class="full quick-row"><div><strong>${esc(o.fullName)}</strong><small>${esc(o.phone)} · ${esc(o.email||'')}</small></div><strong>${money(o.total)}</strong></div><label><span>الحالة</span><select name="status">${['new','confirmed','preparing','ready','shipped','completed','cancelled'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></label><label><span>طريقة الدفع</span><input value="${esc(o.paymentMethod)}" disabled></label><label class="full"><span>العنوان</span><input value="${esc(o.address)}" disabled></label><label class="full"><span>ملاحظة داخلية</span><textarea name="internalNote" rows="4">${esc(o.internalNote)}</textarea></label><div class="full"><h4>المنتجات</h4>${(o.items||[]).map(i=>`<div class="quick-row"><span>${esc(i.name||`منتج #${i.productId||i.id||''}`)} × ${i.quantity||1}</span><strong>${money(i.price||0)}</strong></div>`).join('')||'لا توجد تفاصيل منتجات'}</div><div class="full row-actions"><button class="btn primary" type="submit">حفظ</button><button class="btn ghost" type="button" onclick="window.print()">طباعة</button>${['owner','admin'].includes(state.me?.role)?`<button class="btn ghost danger-text" type="button" onclick="deleteOrder(${id})">حذف الطلب</button>`:''}</div></div>`,async e=>{e.preventDefault();const f=e.currentTarget;try{await api(`/api/admin/orders/${id}`,{method:'PATCH',body:JSON.stringify({status:f.status.value,internalNote:f.internalNote.value})});state.orders=await api('/api/admin/orders');state.overview=await api('/api/admin/overview');renderOrders();renderOverview();closeModal();toast('تم تحديث الطلب')}catch(err){toast(err.message,true)}})};
window.deleteOrder=async function(id){if(!confirm('هل أنت متأكد من حذف الطلب؟ سيتم استخدام Soft Delete.'))return;try{await api(`/api/admin/orders/${id}`,{method:'DELETE'});state.orders=await api('/api/admin/orders');state.overview=await api('/api/admin/overview');renderOrders();renderOverview();closeModal();toast('تم حذف الطلب ويمكن الاحتفاظ به في قاعدة البيانات للاسترجاع')}catch(e){toast(e.message,true)}};

function renderCustomers(){ $('#customersBody').innerHTML=state.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.email||'—')}</td><td>${c.orderCount}</td><td>${money(c.totalSpent)}</td><td>${dateTime(c.lastOrderAt)}</td><td><button class="btn small" onclick="openCustomer('${esc(c.phone)}')">السجل</button></td></tr>`).join('')||'<tr><td colspan="7">لا يوجد عملاء.</td></tr>'; }
window.openCustomer=async function(phone){try{const c=await api('/api/admin/customers/'+encodeURIComponent(phone));openModal(`سجل العميل — ${esc(c.name||phone)}`,`<div class="quick-row"><div><strong>${esc(c.name||'')}</strong><small>${esc(c.phone||'')} · ${esc(c.email||'')}</small></div><strong>${money(c.totalSpent||0)}</strong></div><div style="margin-top:16px">${ordersTable(c.orders||[],true)}</div>`,null)}catch(e){toast(e.message,true)}};
function renderStock(){ const ps=state.products.filter(p=>p.trackStock); $('#stockGrid').innerHTML=ps.map(p=>`<article class="stock-card"><header><div><h4>${esc(p.name)}</h4><p>${esc(p.sku||p.category)}</p></div>${stockBadge(p)}</header><div class="stock-controls"><input id="stock-${p.id}" type="number" min="0" value="${p.stockQty}"><button class="btn small primary" onclick="saveStock(${p.id})">حفظ</button></div></article>`).join('')||'<div class="stock-card">لا توجد منتجات مفعّل لها تتبع المخزون.</div>'; }
window.saveStock=async id=>{const q=+$('#stock-'+id).value||0;try{await api(`/api/admin/products/${id}/stock?quantity=${q}`,{method:'PATCH'});await refreshCore();toast('تم تحديث المخزون')}catch(e){toast(e.message,true)}};

function renderEntities(){
  $('#categoriesGrid').innerHTML=entityCards(state.categories,'category'); $('#brandsGrid').innerHTML=entityCards(state.brands,'brand');
}
function entityCards(rows,type){return rows.map(x=>`<article class="entity-card"><header><div><h4>${esc(x.name)}</h4><p>${x.isActive?'مفعل':'غير مفعل'}</p></div>${x.image?`<img class="thumb" src="${esc(x.image)}">`:''}</header><p>${esc(x.description||'')}</p><div class="row-actions"><button class="btn small" onclick="editEntity('${type}',${x.id})">تعديل</button><button class="btn small ghost danger-text" onclick="deleteEntity('${type}',${x.id})">حذف</button></div></article>`).join('')||'<div class="entity-card">لا توجد عناصر.</div>'}
$$('[data-add-entity]').forEach(b=>b.addEventListener('click',()=>editEntity(b.dataset.addEntity)));
window.editEntity=function(type,id){const list=type==='category'?state.categories:state.brands;const x=id?list.find(v=>v.id===id):{name:'',image:'',description:'',sortOrder:0,isActive:true};const ar=type==='category'?'تصنيف':'ماركة';openModal(id?`تعديل ${ar}`:`إضافة ${ar}`,`<div class="form-grid"><label><span>الاسم</span><input name="name" value="${esc(x.name)}" required></label><label><span>الترتيب</span><input name="sortOrder" type="number" value="${x.sortOrder||0}"></label><label class="full"><span>صورة / شعار</span><input name="image" value="${esc(x.image||'')}"></label><label class="full"><span>الوصف</span><textarea name="description">${esc(x.description||'')}</textarea></label><label><span>الحالة</span><select name="isActive"><option value="1" ${x.isActive?'selected':''}>مفعل</option><option value="0" ${!x.isActive?'selected':''}>معطل</option></select></label><div class="full"><button class="btn primary" type="submit">حفظ</button></div></div>`,async e=>{e.preventDefault();const f=e.currentTarget,p={name:f.name.value.trim(),image:f.image.value.trim(),description:f.description.value.trim(),sortOrder:+f.sortOrder.value||0,isActive:f.isActive.value==='1'};try{await api(`/api/admin/${type==='category'?'categories':'brands'}${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(p)});closeModal();state[type==='category'?'categories':'brands']=await api(`/api/admin/${type==='category'?'categories':'brands'}`);renderEntities();fillFilters();toast('تم الحفظ')}catch(err){toast(err.message,true)}})};
window.deleteEntity=async(type,id)=>{if(!confirm('تأكيد الحذف؟'))return;try{await api(`/api/admin/${type==='category'?'categories':'brands'}/${id}`,{method:'DELETE'});state[type==='category'?'categories':'brands']=await api(`/api/admin/${type==='category'?'categories':'brands'}`);renderEntities();fillFilters();toast('تم الحذف')}catch(e){toast(e.message,true)}};

function renderCoupons(){ $('#couponsGrid').innerHTML=state.coupons.map(c=>`<article class="entity-card"><header><h4>${esc(c.code)}</h4>${badge(c.isActive?'مفعل':'معطل',c.isActive?'good':'')}</header><p>${c.discountType==='percent'?`${c.discountValue}%`:`${money(c.discountValue)}`} · الحد الأدنى ${money(c.minOrder)}</p><p>الاستخدام ${c.usedCount}${c.maxUses!=null?` / ${c.maxUses}`:''}</p><div class="row-actions"><button class="btn small" onclick="editCoupon(${c.id})">تعديل</button><button class="btn small ghost danger-text" onclick="deleteCoupon(${c.id})">حذف</button></div></article>`).join('')||'<div class="entity-card">لا توجد كوبونات.</div>'; }
$('#addCouponBtn').addEventListener('click',()=>editCoupon());
window.editCoupon=function(id){const c=id?state.coupons.find(x=>x.id===id):{code:'',discountType:'percent',discountValue:10,minOrder:0,startsAt:null,endsAt:null,maxUses:null,isActive:true};openModal(id?'تعديل الكوبون':'كوبون جديد',`<div class="form-grid"><label><span>الكود</span><input name="code" value="${esc(c.code)}" required></label><label><span>نوع الخصم</span><select name="discountType"><option value="percent" ${c.discountType==='percent'?'selected':''}>نسبة %</option><option value="fixed" ${c.discountType==='fixed'?'selected':''}>مبلغ ثابت</option></select></label><label><span>قيمة الخصم</span><input name="discountValue" type="number" step="0.01" value="${c.discountValue}"></label><label><span>الحد الأدنى</span><input name="minOrder" type="number" step="0.01" value="${c.minOrder}"></label><label><span>البداية</span><input name="startsAt" type="datetime-local" value="${dateInput(c.startsAt)}"></label><label><span>النهاية</span><input name="endsAt" type="datetime-local" value="${dateInput(c.endsAt)}"></label><label><span>أقصى استخدام</span><input name="maxUses" type="number" value="${c.maxUses??''}"></label><label><span>الحالة</span><select name="isActive"><option value="1" ${c.isActive?'selected':''}>مفعل</option><option value="0" ${!c.isActive?'selected':''}>معطل</option></select></label><div class="full"><button class="btn primary" type="submit">حفظ</button></div></div>`,async e=>{e.preventDefault();const f=e.currentTarget,p={code:f.code.value.trim(),discountType:f.discountType.value,discountValue:+f.discountValue.value||0,minOrder:+f.minOrder.value||0,startsAt:toTs(f.startsAt.value),endsAt:toTs(f.endsAt.value),maxUses:f.maxUses.value?+f.maxUses.value:null,isActive:f.isActive.value==='1'};try{await api(`/api/admin/coupons${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(p)});state.coupons=await api('/api/admin/coupons');renderCoupons();closeModal();toast('تم حفظ الكوبون')}catch(err){toast(err.message,true)}})};
window.deleteCoupon=async id=>{if(!confirm('حذف الكوبون؟'))return;try{await api(`/api/admin/coupons/${id}`,{method:'DELETE'});state.coupons=await api('/api/admin/coupons');renderCoupons();toast('تم الحذف')}catch(e){toast(e.message,true)}};

function renderHomepage(){
  $('#homepageSections').innerHTML=state.homepage.map(s=>`<article class="home-section" data-key="${s.key}"><div class="home-section-head"><div class="home-section-title"><i class="fa-solid fa-grip-vertical"></i><div><strong>${esc(s.title)}</strong><small>${s.isVisible?' ظاهر':' مخفي'} · ترتيب ${s.sortOrder}</small></div></div><div class="row-actions"><button class="btn small" onclick="editHomeSection('${s.key}')">إعدادات القسم</button></div></div><div class="slots-grid" data-slots="${s.key}">${[0,1,2,3].map(i=>slotHtml(s,i)).join('')}</div></article>`).join('');
  state.homepage.forEach(s=>enableSlotDrag(s.key));
}
function slotHtml(section,index){const item=section.items[index];if(!item)return `<div class="slot-card" data-index="${index}"><div class="slot-empty"><button class="btn small primary" onclick="chooseHomeProduct('${section.key}',${index})"><i class="fa-solid fa-plus"></i> اختر منتج</button></div></div>`;const p=item.product;return `<div class="slot-card" draggable="true" data-index="${index}">${p.images?.[0]?`<img src="${esc(p.images[0])}">`:''}<strong>${esc(p.name)}</strong><small>${money(item.customPrice??p.price)}</small><div class="row-actions"><button class="btn small" onclick="chooseHomeProduct('${section.key}',${index})">تغيير</button>${['offers','coming_soon'].includes(section.key)?`<button class="btn small" onclick="editHomeItem('${section.key}',${index})">تفاصيل</button>`:''}<button class="btn small ghost danger-text" onclick="removeHomeProduct('${section.key}',${index})">حذف</button></div></div>`}
window.editHomeSection=function(key){const s=state.homepage.find(x=>x.key===key);openModal('إعدادات القسم',`<div class="form-grid"><label class="full"><span>عنوان القسم</span><input name="title" value="${esc(s.title)}"></label><label><span>الترتيب</span><input name="sortOrder" type="number" value="${s.sortOrder}"></label><label><span>الظهور</span><select name="isVisible"><option value="1" ${s.isVisible?'selected':''}>ظاهر</option><option value="0" ${!s.isVisible?'selected':''}>مخفي</option></select></label><div class="full"><button class="btn primary" type="submit">حفظ</button></div></div>`,async e=>{e.preventDefault();const f=e.currentTarget;try{await api(`/api/admin/homepage/${key}`,{method:'PUT',body:JSON.stringify({title:f.title.value.trim(),sortOrder:+f.sortOrder.value||0,isVisible:f.isVisible.value==='1'})});state.homepage=await api('/api/admin/homepage');renderHomepage();closeModal();toast('تم تحديث القسم')}catch(err){toast(err.message,true)}})};
window.chooseHomeProduct=function(key,index){const s=state.homepage.find(x=>x.key===key);openModal('اختيار المنتج',`<input id="pickSearch" placeholder="ابحث عن منتج"><div id="pickList" class="select-list"></div>`,null);const draw=()=>{const q=$('#pickSearch').value.toLowerCase();$('#pickList').innerHTML=state.products.filter(p=>p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)).map(p=>`<button type="button" class="select-product" onclick="setHomeProduct('${key}',${index},${p.id})">${p.images?.[0]?`<img src="${esc(p.images[0])}">`:''}<strong>${esc(p.name)}</strong><small>${money(p.price)}</small></button>`).join('')};draw();$('#pickSearch').addEventListener('input',draw)};
window.setHomeProduct=async function(key,index,pid){const s=state.homepage.find(x=>x.key===key);const items=[...s.items];while(items.length<=index)items.push(null);items[index]={product:state.products.find(p=>p.id===pid),customPrice:null,startsAt:null,endsAt:null};const clean=items.filter(Boolean);try{await saveHomeItems(key,clean);closeModal()}catch(e){toast(e.message,true)}};
window.editHomeItem=function(key,index){const section=state.homepage.find(x=>x.key===key);const item=section?.items[index];if(!item)return;const title=key==='offers'?'تفاصيل العرض':'تفاصيل قريبًا';const priceLabel=key==='offers'?'السعر الخاص بعد الخصم':'السعر المتوقع (اختياري)';openModal(title,`<div class="form-grid"><label><span>${priceLabel}</span><input name="customPrice" type="number" step="0.01" value="${item.customPrice??''}"></label><label><span>تاريخ البداية / الظهور</span><input name="startsAt" type="datetime-local" value="${dateInput(item.startsAt)}"></label><label><span>تاريخ النهاية (اختياري)</span><input name="endsAt" type="datetime-local" value="${dateInput(item.endsAt)}"></label><div class="full"><button class="btn primary" type="submit">حفظ التفاصيل</button></div></div>`,async e=>{e.preventDefault();const f=e.currentTarget;const items=section.items.map((x,i)=>i===index?{...x,customPrice:f.customPrice.value?+f.customPrice.value:null,startsAt:toTs(f.startsAt.value),endsAt:toTs(f.endsAt.value)}:x);try{await saveHomeItems(key,items);closeModal()}catch(err){toast(err.message,true)}})};
window.removeHomeProduct=async function(key,index){const s=state.homepage.find(x=>x.key===key);const items=s.items.filter((_,i)=>i!==index);try{await saveHomeItems(key,items)}catch(e){toast(e.message,true)}};
async function saveHomeItems(key,items){await api(`/api/admin/homepage/${key}/items`,{method:'PUT',body:JSON.stringify({items:items.map(x=>({productId:x.product.id,customPrice:x.customPrice??null,startsAt:x.startsAt??null,endsAt:x.endsAt??null}))})});state.homepage=await api('/api/admin/homepage');renderHomepage();toast('تم حفظ منتجات القسم')}
function enableSlotDrag(key){const root=$(`[data-slots="${key}"]`);let from=null;root.querySelectorAll('.slot-card[draggable=true]').forEach(card=>{card.addEventListener('dragstart',()=>{from=+card.dataset.index;card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'));card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',async()=>{const to=+card.dataset.index;if(from===null||from===to)return;const s=state.homepage.find(x=>x.key===key);const items=[...s.items];[items[from],items[to]]=[items[to],items[from]];await saveHomeItems(key,items.filter(Boolean))})})}

function popupImageSetting(settings=state.settings||{}){return settingHas(settings,'popup_image_url','popupImageUrl')?String(settingValue(settings,'popup_image_url','popupImageUrl')||''):DEFAULT_POPUP_IMAGE_URL}
function renderPopupAdSettings(){const f=$('#popupForm');if(!f)return;const s=state.settings||{};f.popup_enabled.value=boolSetting(settingValue(s,'popup_enabled','popupEnabled'),true)?'1':'0';f.popup_image_url.value=popupImageSetting(s);updatePopupPreview(f.popup_image_url.value)}
function updatePopupPreview(url){const box=$('#popupPreviewBox'),img=$('#popupImagePreview');if(!box||!img)return;const src=String(url||'').trim();box.hidden=!src;if(src)img.src=src;else img.removeAttribute('src')}
$('#popupImageUpload')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;updatePopupPreview(URL.createObjectURL(file))});
$('#removePopupImageBtn')?.addEventListener('click',()=>{const f=$('#popupForm');if(!f)return;f.popup_image_url.value='';$('#popupImageUpload').value='';updatePopupPreview('')});
$('#popupForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const uploaded=await uploadImageInput('#popupImageUpload','#popupUploadHint');const patch={popup_enabled:f.popup_enabled.value==='1',popup_image_url:uploaded||f.popup_image_url.value.trim()};await saveSettingsPatch(patch);$('#popupImageUpload').value='';renderPopupAdSettings();toast('تم حفظ إعلان فتح الموقع')}catch(err){toast(err.message,true)}});

function renderBanners(){
  renderPopupAdSettings();
  $('#slidesGrid').innerHTML=state.slides.map(x=>`<article class="entity-card"><header><h4>${esc(x.title||'بانر')}</h4>${badge(x.isActive?'مفعل':'معطل',x.isActive?'good':'')}</header>${x.imageUrl?`<img style="width:100%;height:130px;object-fit:cover;border-radius:12px;margin-top:8px" src="${esc(x.imageUrl)}">`:''}<p>${esc(x.description)}</p><div class="row-actions"><button class="btn small" onclick="editSlide(${x.id})">تعديل</button><button class="btn small ghost danger-text" onclick="deleteSlide(${x.id})">حذف</button></div></article>`).join('')||'<div class="entity-card">لا توجد بانرات.</div>';
  $('#adsGrid').innerHTML=state.ads.map(x=>`<article class="entity-card"><header><h4>${esc(x.title||'إعلان')}</h4>${badge(x.is_active?'مفعل':'معطل',x.is_active?'good':'')}</header><p>${esc(x.text||'')}</p><p>${esc(x.placement||'home')}</p><div class="row-actions"><button class="btn small" onclick="editAd(${x.id})">تعديل</button><button class="btn small ghost danger-text" onclick="deleteAd(${x.id})">حذف</button></div></article>`).join('')||'<div class="entity-card">لا توجد إعلانات.</div>';
}
$('#addSlideBtn').addEventListener('click',()=>editSlide());$('#addAdBtn').addEventListener('click',()=>editAd());
window.editSlide=function(id){
  const x=id?state.slides.find(v=>v.id===id):{badge:'',title:'',description:'',imageUrl:'',imageAlt:'',primaryButtonText:'',primaryButtonLink:'',secondaryButtonText:'',secondaryButtonLink:'',productId:null,sortOrder:0,isActive:true};
  openModal(id?'تعديل البانر':'بانر جديد',`<div class="form-grid"><label><span>Badge</span><input name="badge" value="${esc(x.badge)}"></label><label><span>العنوان</span><input name="title" value="${esc(x.title)}"></label><label class="full"><span>النص</span><textarea name="description">${esc(x.description)}</textarea></label><label class="full"><span>صورة الخلفية</span><input name="imageUrl" value="${esc(x.imageUrl)}"></label><label class="full"><span>أو ارفع صورة بانر</span><input id="slideImageUpload" type="file" accept="image/*"></label><div id="slideUploadHint" class="hint full"></div><label><span>CTA</span><input name="primaryButtonText" value="${esc(x.primaryButtonText)}"></label><label><span>رابط CTA</span><input name="primaryButtonLink" value="${esc(x.primaryButtonLink)}"></label><label><span>الترتيب</span><input name="sortOrder" type="number" value="${x.sortOrder||0}"></label><label><span>الحالة</span><select name="isActive"><option value="1" ${x.isActive?'selected':''}>مفعل</option><option value="0" ${!x.isActive?'selected':''}>معطل</option></select></label><div class="full"><button class="btn primary" type="submit">حفظ</button></div></div>`,async e=>{
    e.preventDefault();const f=e.currentTarget;
    try{
      const uploaded=await uploadImageInput('#slideImageUpload','#slideUploadHint');
      const p={badge:f.badge.value,title:f.title.value,description:f.description.value,imageUrl:uploaded||f.imageUrl.value,imageAlt:'',primaryButtonText:f.primaryButtonText.value,primaryButtonLink:f.primaryButtonLink.value,secondaryButtonText:'',secondaryButtonLink:'',productId:null,sortOrder:+f.sortOrder.value||0,isActive:f.isActive.value==='1'};
      await api(`/api/admin/hero-slides${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(p)});state.slides=await api('/api/admin/hero-slides');renderBanners();closeModal();toast('تم حفظ البانر')
    }catch(err){toast(err.message,true)}
  });
};
window.deleteSlide=async id=>{if(!confirm('حذف البانر؟'))return;try{await api(`/api/admin/hero-slides/${id}`,{method:'DELETE'});state.slides=await api('/api/admin/hero-slides');renderBanners();toast('تم الحذف')}catch(e){toast(e.message,true)}};
window.editAd=function(id){
  const x=id?state.ads.find(v=>v.id===id):{title:'',text:'',image_url:'',link_url:'',placement:'home',starts_at:null,ends_at:null,is_active:1};
  openModal(id?'تعديل الإعلان':'إعلان جديد',`<div class="form-grid"><label><span>العنوان</span><input name="title" value="${esc(x.title)}"></label><label><span>مكان الظهور</span><input name="placement" value="${esc(x.placement||'home')}"></label><label class="full"><span>النص</span><textarea name="text">${esc(x.text||'')}</textarea></label><label class="full"><span>الصورة</span><input name="imageUrl" value="${esc(x.image_url||'')}"></label><label class="full"><span>أو ارفع صورة إعلان</span><input id="adImageUpload" type="file" accept="image/*"></label><div id="adUploadHint" class="hint full"></div><label class="full"><span>الرابط</span><input name="linkUrl" value="${esc(x.link_url||'')}"></label><label><span>البداية</span><input name="startsAt" type="datetime-local" value="${dateInput(x.starts_at)}"></label><label><span>النهاية</span><input name="endsAt" type="datetime-local" value="${dateInput(x.ends_at)}"></label><label><span>الحالة</span><select name="isActive"><option value="1" ${x.is_active?'selected':''}>مفعل</option><option value="0" ${!x.is_active?'selected':''}>معطل</option></select></label><div class="full"><button class="btn primary" type="submit">حفظ</button></div></div>`,async e=>{
    e.preventDefault();const f=e.currentTarget;
    try{
      const uploaded=await uploadImageInput('#adImageUpload','#adUploadHint');
      const p={title:f.title.value,text:f.text.value,imageUrl:uploaded||f.imageUrl.value,linkUrl:f.linkUrl.value,placement:f.placement.value,startsAt:toTs(f.startsAt.value),endsAt:toTs(f.endsAt.value),isActive:f.isActive.value==='1'};
      await api(`/api/admin/ads${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(p)});state.ads=await api('/api/admin/ads');renderBanners();closeModal();toast('تم حفظ الإعلان')
    }catch(err){toast(err.message,true)}
  });
};
window.deleteAd=async id=>{if(!confirm('حذف الإعلان؟'))return;try{await api(`/api/admin/ads/${id}`,{method:'DELETE'});state.ads=await api('/api/admin/ads');renderBanners();toast('تم الحذف')}catch(e){toast(e.message,true)}};

function renderUsers(){const root=$('#usersGrid');if(!root)return;root.innerHTML=(state.users||[]).map(u=>`<article class="entity-card"><header><h4>${esc(u.username)}</h4>${badge(u.role)}</header><p>${u.isActive?'نشط':'موقوف'}</p><button class="btn small" onclick="editUser(${u.id})">تعديل</button></article>`).join('')||'<div class="entity-card">لا يوجد مستخدمون.</div>'}
$('#addUserBtn').addEventListener('click',()=>editUser());
window.editUser=function(id){const u=id?state.users.find(x=>x.id===id):{email:'',userId:'',username:'',role:'employee',isActive:true};openModal(id?'تعديل صلاحية الأدمن':'إضافة صلاحية لمستخدم Auth',`<div class="form-grid"><label><span>البريد الإلكتروني</span><input name="email" type="email" value="${esc(u.email||u.username)}" ${id?'disabled':''} required></label>${id?'':`<label class="full"><span>Supabase Auth User ID</span><input name="userId" value="${esc(u.userId||'')}" required></label>`}<label><span>الدور</span><select name="role"><option value="owner" ${u.role==='owner'?'selected':''}>Owner</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option><option value="employee" ${u.role==='employee'?'selected':''}>Employee</option></select></label><label><span>الحالة</span><select name="isActive"><option value="1" ${u.isActive?'selected':''}>نشط</option><option value="0" ${!u.isActive?'selected':''}>موقوف</option></select></label><p class="full hint">أنشئ المستخدم وكلمة مروره من Supabase Auth أولاً، ثم أضف User ID هنا. لا يتم استخدام Service Key داخل الواجهة.</p><div class="full"><button class="btn primary" type="submit">حفظ</button></div></div>`,async e=>{e.preventDefault();const f=e.currentTarget,p=id?{role:f.role.value,isActive:f.isActive.value==='1'}:{email:f.email.value.trim(),username:f.email.value.trim(),userId:f.userId.value.trim(),role:f.role.value,isActive:f.isActive.value==='1'};try{await api(`/api/admin/users${id?'/'+id:''}`,{method:id?'PATCH':'POST',body:JSON.stringify(p)});state.users=await api('/api/admin/users');renderUsers();closeModal();toast('تم حفظ الصلاحية')}catch(err){toast(err.message,true)}})};
function renderActivity(){const root=$('#activityList');if(!root)return;root.innerHTML=(state.activity||[]).map(a=>`<div class="activity-row"><strong>${esc(a.username)}</strong><div>${esc(a.action)} <small>${esc(a.entity_type)} ${esc(a.entity_id)}</small><br><small>${esc(a.details||'')}</small></div><small>${dateTime(a.created_at)}</small></div>`).join('')||'<div>لا توجد عمليات.</div>'}

function renderSettings(){const s=state.settings||{};const f=$('#settingsForm');['storeName','logo','favicon','phone','whatsapp','email','facebook','instagram','tiktok','address','workingHours'].forEach(k=>{if(f.elements[k])f.elements[k].value=s[k]||''});f.pay_cash.checked=!!s.paymentMethods?.cash;f.pay_bank.checked=!!s.paymentMethods?.bank;f.pay_usdt.checked=!!s.paymentMethods?.usdt;f.pay_cod.checked=!!s.paymentMethods?.cod;f.shippingPrice.value=s.shipping?.defaultPrice||0;f.freeAbove.value=s.shipping?.freeAbove||0;f.regions.value=(s.shipping?.regions||[]).join('\n');if(f.cart_discount_enabled)f.cart_discount_enabled.value=boolSetting(settingValue(s,'cart_discount_enabled','cartDiscountEnabled'),true)?'1':'0';if(f.cart_discount_percent)f.cart_discount_percent.value=percentSetting(settingValue(s,'cart_discount_percent','cartDiscountPercent'),DEFAULT_CART_DISCOUNT_PERCENT)}
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,p={storeName:f.storeName.value,logo:f.logo.value,favicon:f.favicon.value,phone:f.phone.value,whatsapp:f.whatsapp.value,email:f.email.value,facebook:f.facebook.value,instagram:f.instagram.value,tiktok:f.tiktok.value,address:f.address.value,workingHours:f.workingHours.value,paymentMethods:{cash:f.pay_cash.checked,bank:f.pay_bank.checked,usdt:f.pay_usdt.checked,cod:f.pay_cod.checked},shipping:{defaultPrice:+f.shippingPrice.value||0,freeAbove:+f.freeAbove.value||0,regions:f.regions.value.split('\n').map(s=>s.trim()).filter(Boolean)},cart_discount_enabled:f.cart_discount_enabled?.value==='1',cart_discount_percent:percentSetting(f.cart_discount_percent?.value,DEFAULT_CART_DISCOUNT_PERCENT)};try{await saveSettingsPatch(p);renderSettings();renderPopupAdSettings();toast('تم حفظ الإعدادات')}catch(err){toast(err.message,true)}});

let searchTimer;
$('#globalSearch').addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();if(!q){$('#searchResults').classList.add('hidden');return}searchTimer=setTimeout(async()=>{try{const d=await api('/api/admin/search?q='+encodeURIComponent(q));const html=[...d.products.map(p=>`<div class="search-item" onclick="switchSection('products')"><strong>${esc(p.name)}</strong><small>منتج · ${esc(p.sku||p.brand)}</small></div>`),...d.orders.map(o=>`<div class="search-item" onclick="openOrder(${o.id})"><strong>طلب #${o.id} — ${esc(o.fullName)}</strong><small>${esc(o.phone)}</small></div>`),...d.customers.map(c=>`<div class="search-item" onclick="switchSection('customers')"><strong>${esc(c.name)}</strong><small>${esc(c.phone)}</small></div>`)].join('');$('#searchResults').innerHTML=html||'<div class="search-item">لا توجد نتائج.</div>';$('#searchResults').classList.remove('hidden')}catch(err){toast(err.message,true)}},250)});

document.addEventListener('click',e=>{if(!e.target.closest('.global-search'))$('#searchResults').classList.add('hidden')});
(async()=>{ if(await window.SwitchesSupabaseAdmin?.hasSession?.()) boot(); else showAuth(); })();
