-- Switches Store Gift Cards admin data model.
-- Apply manually in Supabase SQL editor. Do not expose a service_role key in the frontend.

create table if not exists public.gift_cards (
  id bigint generated by default as identity primary key,
  name text not null,
  display_name text not null,
  short_name text,
  slug text not null unique,
  description text default '',
  region_code text not null default 'US',
  region_label text not null default 'ريجن أمريكي',
  currency text not null default 'USD',
  image_url text default '',
  background_url text default '',
  icon_class text default 'fa-solid fa-gift',
  accent text default '#7c3aed',
  status text not null default 'AVAILABLE' check (status in ('AVAILABLE', 'COMING_SOON', 'UNAVAILABLE', 'HIDDEN')),
  sort_order integer not null default 0,
  is_deleted boolean not null default false,
  created_at bigint not null default extract(epoch from now())::bigint,
  updated_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.gift_card_denominations (
  id bigint generated by default as identity primary key,
  gift_card_id bigint not null references public.gift_cards(id) on delete cascade,
  face_value numeric(12, 2) not null,
  currency text not null default 'USD',
  selling_price_lyd numeric(12, 2) not null default 0,
  is_available boolean not null default true,
  is_most_popular boolean not null default false,
  highlight_effect text not null default 'none' check (highlight_effect in ('none', 'flame')),
  sort_order integer not null default 0,
  created_at bigint not null default extract(epoch from now())::bigint,
  updated_at bigint not null default extract(epoch from now())::bigint,
  unique (gift_card_id, currency, face_value)
);

create index if not exists idx_gift_cards_status_sort on public.gift_cards(status, sort_order, name);
create index if not exists idx_gift_cards_slug on public.gift_cards(slug);
create index if not exists idx_gift_card_denominations_card_sort on public.gift_card_denominations(gift_card_id, sort_order, face_value);

alter table public.gift_cards enable row level security;
alter table public.gift_card_denominations enable row level security;

drop policy if exists "Public can read visible gift cards" on public.gift_cards;
drop policy if exists "Admins can read gift cards" on public.gift_cards;
drop policy if exists "Owners and admins can write gift cards" on public.gift_cards;
drop policy if exists "Public can read visible gift card denominations" on public.gift_card_denominations;
drop policy if exists "Admins can read gift card denominations" on public.gift_card_denominations;
drop policy if exists "Owners and admins can write gift card denominations" on public.gift_card_denominations;

create policy "Public can read visible gift cards"
on public.gift_cards for select
using (is_deleted = false and status <> 'HIDDEN');

create policy "Admins can read gift cards"
on public.gift_cards for select
using (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = auth.uid()
      and ap.is_active = true
      and ap.role in ('owner', 'admin', 'employee')
  )
);

create policy "Owners and admins can write gift cards"
on public.gift_cards for all
using (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = auth.uid()
      and ap.is_active = true
      and ap.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = auth.uid()
      and ap.is_active = true
      and ap.role in ('owner', 'admin')
  )
);

create policy "Public can read visible gift card denominations"
on public.gift_card_denominations for select
using (
  exists (
    select 1 from public.gift_cards gc
    where gc.id = gift_card_id
      and gc.is_deleted = false
      and gc.status <> 'HIDDEN'
  )
);

create policy "Admins can read gift card denominations"
on public.gift_card_denominations for select
using (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = auth.uid()
      and ap.is_active = true
      and ap.role in ('owner', 'admin', 'employee')
  )
);

create policy "Owners and admins can write gift card denominations"
on public.gift_card_denominations for all
using (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = auth.uid()
      and ap.is_active = true
      and ap.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = auth.uid()
      and ap.is_active = true
      and ap.role in ('owner', 'admin')
  )
);

insert into public.gift_cards
  (name, display_name, short_name, slug, description, region_code, region_label, currency, image_url, background_url, icon_class, accent, status, sort_order, is_deleted, created_at, updated_at)
values
  ('PlayStation Store', 'PlayStation Store', 'PlayStation', 'playstation', 'بطاقات PlayStation Store ريجن أمريكي.', 'US', 'ريجن أمريكي', 'USD', '/assets/gift-cards/playstation.avif', '/assets/gift-cards/playstation.avif', 'fa-brands fa-playstation', '#2563eb', 'AVAILABLE', 20, false, extract(epoch from now())::bigint, extract(epoch from now())::bigint),
  ('Xbox', 'Xbox', 'Xbox', 'xbox', 'بطاقات Xbox و Microsoft Store ريجن أمريكي.', 'US', 'ريجن أمريكي', 'USD', '/assets/gift-cards/xbox.avif', '/assets/gift-cards/xbox.avif', 'fa-brands fa-xbox', '#16a34a', 'AVAILABLE', 30, false, extract(epoch from now())::bigint, extract(epoch from now())::bigint),
  ('Steam Wallet', 'Steam Wallet', 'Steam', 'steam', 'رصيد Steam Wallet للألعاب والمحتوى الرقمي.', 'US', 'ريجن أمريكي', 'USD', '/assets/gift-cards/steam.avif', '/assets/gift-cards/steam.avif', 'fa-brands fa-steam', '#38bdf8', 'COMING_SOON', 10, false, extract(epoch from now())::bigint, extract(epoch from now())::bigint),
  ('Apple Gift Card', 'Apple Gift Card', 'Apple', 'apple', 'بطاقات Apple للخدمات والتطبيقات والاشتراكات.', 'US', 'ريجن أمريكي', 'USD', '/assets/gift-cards/apple.avif', '/assets/gift-cards/apple.avif', 'fa-brands fa-apple', '#f8fafc', 'COMING_SOON', 40, false, extract(epoch from now())::bigint, extract(epoch from now())::bigint),
  ('Amazon Gift Card', 'Amazon Gift Card', 'Amazon', 'amazon', 'بطاقات Amazon للمناطق المدعومة.', 'US', 'ريجن أمريكي', 'USD', '/assets/gift-cards/amazon.webp', '/assets/gift-cards/amazon.webp', 'fa-brands fa-amazon', '#f59e0b', 'COMING_SOON', 50, false, extract(epoch from now())::bigint, extract(epoch from now())::bigint),
  ('Google Play', 'Google Play', 'Google Play', 'google-play', 'رصيد Google Play للتطبيقات والألعاب.', 'US', 'ريجن أمريكي', 'USD', '/assets/gift-cards/google-play.svg', '/assets/gift-cards/google-play.svg', 'fa-brands fa-google-play', '#22c55e', 'COMING_SOON', 60, false, extract(epoch from now())::bigint, extract(epoch from now())::bigint)
on conflict (slug) do update set
  name = excluded.name,
  display_name = excluded.display_name,
  short_name = excluded.short_name,
  description = excluded.description,
  region_code = excluded.region_code,
  region_label = excluded.region_label,
  currency = excluded.currency,
  image_url = excluded.image_url,
  background_url = excluded.background_url,
  icon_class = excluded.icon_class,
  accent = excluded.accent,
  status = excluded.status,
  sort_order = excluded.sort_order,
  is_deleted = false,
  updated_at = extract(epoch from now())::bigint;

with card as (select id from public.gift_cards where slug = 'playstation')
insert into public.gift_card_denominations
  (gift_card_id, face_value, currency, selling_price_lyd, is_available, is_most_popular, highlight_effect, sort_order, created_at, updated_at)
select card.id, v.face_value, 'USD', v.price, true, v.face_value = 50, case when v.face_value = 50 then 'flame' else 'none' end, v.sort_order, extract(epoch from now())::bigint, extract(epoch from now())::bigint
from card, (values
  (25, 267.50, 10), (30, 315.00, 20), (40, 420.00, 30), (50, 525.00, 40),
  (60, 618.00, 50), (70, 721.00, 60), (75, 772.50, 70), (80, 824.00, 80),
  (90, 927.00, 90), (100, 1030.00, 100), (125, 1281.25, 110), (150, 1537.50, 120),
  (175, 1793.75, 130), (200, 2050.00, 140), (225, 2306.25, 150), (250, 2562.50, 160)
) as v(face_value, price, sort_order)
on conflict (gift_card_id, currency, face_value) do update set
  selling_price_lyd = excluded.selling_price_lyd,
  is_available = excluded.is_available,
  is_most_popular = excluded.is_most_popular,
  highlight_effect = excluded.highlight_effect,
  sort_order = excluded.sort_order,
  updated_at = extract(epoch from now())::bigint;

with card as (select id from public.gift_cards where slug = 'xbox')
insert into public.gift_card_denominations
  (gift_card_id, face_value, currency, selling_price_lyd, is_available, is_most_popular, highlight_effect, sort_order, created_at, updated_at)
select card.id, v.face_value, 'USD', v.price, true, v.face_value = 50, case when v.face_value = 50 then 'flame' else 'none' end, v.sort_order, extract(epoch from now())::bigint, extract(epoch from now())::bigint
from card, (values
  (5, 54.00, 10), (10, 108.00, 20), (15, 162.00, 30), (20, 214.00, 40),
  (25, 267.50, 50), (30, 315.00, 60), (40, 420.00, 70), (50, 525.00, 80),
  (60, 618.00, 90), (70, 721.00, 100), (80, 824.00, 110), (90, 927.00, 120),
  (100, 1030.00, 130)
) as v(face_value, price, sort_order)
on conflict (gift_card_id, currency, face_value) do update set
  selling_price_lyd = excluded.selling_price_lyd,
  is_available = excluded.is_available,
  is_most_popular = excluded.is_most_popular,
  highlight_effect = excluded.highlight_effect,
  sort_order = excluded.sort_order,
  updated_at = extract(epoch from now())::bigint;

with card as (select id from public.gift_cards where slug = 'steam')
insert into public.gift_card_denominations (gift_card_id, face_value, currency, selling_price_lyd, is_available, sort_order, created_at, updated_at)
select card.id, v.face_value, 'USD', v.price, false, v.sort_order, extract(epoch from now())::bigint, extract(epoch from now())::bigint
from card, (values (10, 110.00, 10), (20, 215.00, 20), (50, 525.00, 30), (100, 1030.00, 40)) as v(face_value, price, sort_order)
on conflict (gift_card_id, currency, face_value) do update set selling_price_lyd = excluded.selling_price_lyd, sort_order = excluded.sort_order, updated_at = extract(epoch from now())::bigint;

with card as (select id from public.gift_cards where slug = 'apple')
insert into public.gift_card_denominations (gift_card_id, face_value, currency, selling_price_lyd, is_available, sort_order, created_at, updated_at)
select card.id, v.face_value, 'USD', v.price, false, v.sort_order, extract(epoch from now())::bigint, extract(epoch from now())::bigint
from card, (values (10, 110.00, 10), (25, 267.50, 20), (50, 525.00, 30), (100, 1030.00, 40)) as v(face_value, price, sort_order)
on conflict (gift_card_id, currency, face_value) do update set selling_price_lyd = excluded.selling_price_lyd, sort_order = excluded.sort_order, updated_at = extract(epoch from now())::bigint;

with card as (select id from public.gift_cards where slug = 'google-play')
insert into public.gift_card_denominations (gift_card_id, face_value, currency, selling_price_lyd, is_available, sort_order, created_at, updated_at)
select card.id, v.face_value, 'USD', v.price, false, v.sort_order, extract(epoch from now())::bigint, extract(epoch from now())::bigint
from card, (values (10, 110.00, 10), (25, 267.50, 20), (50, 525.00, 30), (100, 1030.00, 40)) as v(face_value, price, sort_order)
on conflict (gift_card_id, currency, face_value) do update set selling_price_lyd = excluded.selling_price_lyd, sort_order = excluded.sort_order, updated_at = extract(epoch from now())::bigint;

with card as (select id from public.gift_cards where slug = 'amazon')
insert into public.gift_card_denominations (gift_card_id, face_value, currency, selling_price_lyd, is_available, sort_order, created_at, updated_at)
select card.id, v.face_value, 'USD', v.price, false, v.sort_order, extract(epoch from now())::bigint, extract(epoch from now())::bigint
from card, (values (25, 267.50, 10), (50, 525.00, 20)) as v(face_value, price, sort_order)
on conflict (gift_card_id, currency, face_value) do update set selling_price_lyd = excluded.selling_price_lyd, sort_order = excluded.sort_order, updated_at = extract(epoch from now())::bigint;

insert into public.store_settings (id, settings_json, updated_at)
values (1, jsonb_build_object('gift_cards_whatsapp_purchase_number', '218931853169'), extract(epoch from now())::bigint)
on conflict (id) do update set
  settings_json = coalesce(public.store_settings.settings_json, '{}'::jsonb) || excluded.settings_json,
  updated_at = extract(epoch from now())::bigint;
